### ISSUE TITLE
Extended data for company profile 

### ISSUE THREAD

**Issue by lukasrezanina** [epctex/clutchco-scraper#2]
Hey Epctex, 
is it possible to extend data for Clutch API? 

**I miss mainly two information:**

1. In Portfolio - Project title 
2. In Reviews - Whole extended review

Thanks for the reply!

**Comment by tugkan** [comment]
Hey @lukasrezanina !

Thank you very much for reaching out. I just want to inform you that the requests have been implemented and you can retrieve the information by the latest updated version of the actor.

Best

**Comment by lukasrezanina** [comment]
Hey Tugkan, I have tried now and I received a message: "Reclaiming failed request back to the list or queue. We got blocked." Do you know some solution for that?

Thanks and regards Tugkan!

Lukas

**Comment by tugkan** [comment]
Hey @lukasrezanina 

If that is the only message you are retrieving, then the problem is most likely related to your proxies. You can use Residential ones and try again. Because actor blocking is something that we cannot directly impact.
