### ISSUE TITLE
Portfolio items not scraped at all

### ISSUE THREAD

**Issue by lukasrezanina** [epctex/clutchco-scraper#3]
Hey Epctex,

I have a question about portfolio. After few changes in Clutch it failed to scrape me portfolio items in one company listed on Clutch. Is it working properly on your side?

Thanks and regards!
Lukas

**Comment by tugkan** [comment]
Hey @lukasrezanina !

Thank you very much for using our actor and letting us know that you have a problem. It is working properly on our side but maybe we are missing something that it shouldn't be missed. Can you please the company you would like to retrieve the portfolio for?

Best

**Comment by tugkan** [comment]
Closing the comment due to no response. Please let me know if you need any further assistance, and we can reopen it.

**Comment by lukasrezanina** [comment]
Hey Tugkan,

now the portfolio looks like:

{ "image": "
https://img.shgstatic.com/clutchco-static/image/resize/500x350/s3fs-public/portfolio/e0cf1fcb03227caf34a7ef4981411137.jpg
", "description": "Restaurant Chain App Development" }
There is Name -> Description now.

No description and now also these new categories from Clutch in Portfolio

Services Provided on this Project
Mobile App Development
Client

PONS
Project Size

$200,000 to $999,999

Thanks for your check :-)

Regards




*Ing. Lukáš Řezanina* | CEO
+421 905 181 359 (SK) | ***@***.***
Nordics.io <https://nordics.io> | LinkedIn
<https://www.linkedin.com/in/rezanina/>

**Comment by lukasrezanina** [comment]
Hey Tugkan,

now the portfolio looks like:

 {
    "image": "https://img.shgstatic.com/clutchco-static/image/resize/500x350/s3fs-public/portfolio/e0cf1fcb03227caf34a7ef4981411137.jpg",
    "description": "Restaurant Chain App Development"
  }

There is Name -> Description now. 

No description and now also possible to scrape these new categories from Clutch in Portfolio:

Services Provided on this Project:
Mobile App Development
Client:
PONS
Project Size:
$200,000 to $999,999


Thanks for your check :-)

Regards

**Comment by tugkan** [comment]
Hey @lukasrezanina !

I just reopened the issue. I passed the information to the Engineering Team and will let you soon about the updates. The functionality seems doable on our end.

Will keep  you posted.
Best

**Comment by tugkan** [comment]
Hey @lukasrezanina !

I just wanted to let you know that the development has been completed and now all the detailed portfolio data can be retrieved directly from the actor itself. Please use the latest version for the best experience.

Please let me know if there is anything else that I can assist you with. Closing the Issue now but feel free to reopen.
Best
